const TOP_TEAMS = [
    "Golden State Warriors",
    "Raptors",
    "Bucks",
    "Nuggets",
    "76ers",
    "Trail Blazers",
    "Thunder",
    "Grizzlies",
    "Clippers",
    "Lakers",
    "Rockets",
    "Pacers",
    "Celtics",
    "Jazz",
    "Pelicans",
    "Spurs",
    "Hornets",
    "Pistons",
    "Kings",
    "Magic",
    "Timberwolves",
    "Mavericks",
    "Wizards",
    "Nets",
    "Heat",
    "Knicks",
    "Bulls",
    "Suns",
    "Cavaliers",
    "Hawks"
]

module.exports = TOP_TEAMS.reverse()